# Pull base image
# ---------------
FROM oracle/database:18.4.0-xe

# Maintainer
# ----------
MAINTAINER Preston Sheldon <pksiv@hotmail.com>

# TODO: Move this outside of this file
ENV ORACLE_PWD=4dminPass 

COPY scripts/*.sh $ORACLE_BASE/
COPY sql/* $ORACLE_BASE/scripts/sql/

# Builds Oracle DB inside of this image
RUN $ORACLE_BASE/runOracle.sh

# Starts Oracle DB and creates users based on environment variables
CMD $ORACLE_BASE/entrypoint.sh
